/**
 * !!! IMPORTANT: AUTO-GENERATED FILE !!!
 *
 * This file is automatically generated from undefined
 * Do not edit this file directly. Make changes to the source file instead.
 *
 * NOTE: This type copying approach is not meant to be a final solution.
 * A more robust approach would involve generating types from a common schema
 * or using a dedicated code generation tool.
 *
 * Recommended improvement: Create a shared npm package containing all type
 * definitions that can be imported by both Angular and Deno environments.
 * This would ensure type consistency and eliminate manual syncing.
 *
 * Last updated: 2025-04-20T23:39:48.789Z
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  graphql_public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: {
      graphql: {
        Args: {
          operationName?: string
          query?: string
          variables?: Json
          extensions?: Json
        }
        Returns: Json
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
  public: {
    Tables: {
      exercises: {
        Row: {
          description: string | null
          id: string
          name: string
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      session_sets: {
        Row: {
          actual_reps: number
          actual_weight: number
          completed_at: string | null
          id: string
          set_index: number
          status: string
          training_plan_exercise_id: string
          training_session_id: string
        }
        Insert: {
          actual_reps: number
          actual_weight: number
          completed_at?: string | null
          id?: string
          set_index: number
          status?: string
          training_plan_exercise_id: string
          training_session_id: string
        }
        Update: {
          actual_reps?: number
          actual_weight?: number
          completed_at?: string | null
          id?: string
          set_index?: number
          status?: string
          training_plan_exercise_id?: string
          training_session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_series_training_session_id_fkey1"
            columns: ["training_session_id"]
            isOneToOne: false
            referencedRelation: "training_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_sets_training_session_id_fkey"
            columns: ["training_session_id"]
            isOneToOne: false
            referencedRelation: "training_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      training_plan_days: {
        Row: {
          description: string | null
          id: string
          name: string
          order_index: number
          training_plan_id: string
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
          order_index: number
          training_plan_id: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          order_index?: number
          training_plan_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "training_plan_days_training_plan_id_fkey"
            columns: ["training_plan_id"]
            isOneToOne: false
            referencedRelation: "training_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      training_plan_exercise_progressions: {
        Row: {
          consecutive_failures: number
          current_weight: number
          deload_percentage: number
          deload_strategy: string
          exercise_id: string
          failure_count_for_deload: number
          id: string
          last_updated: string | null
          reference_set_index: number | null
          training_plan_id: string
          weight_increment: number
        }
        Insert: {
          consecutive_failures?: number
          current_weight: number
          deload_percentage?: number
          deload_strategy?: string
          exercise_id: string
          failure_count_for_deload?: number
          id?: string
          last_updated?: string | null
          reference_set_index?: number | null
          training_plan_id: string
          weight_increment: number
        }
        Update: {
          consecutive_failures?: number
          current_weight?: number
          deload_percentage?: number
          deload_strategy?: string
          exercise_id?: string
          failure_count_for_deload?: number
          id?: string
          last_updated?: string | null
          reference_set_index?: number | null
          training_plan_id?: string
          weight_increment?: number
        }
        Relationships: [
          {
            foreignKeyName: "training_plan_exercise_progressions_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "training_plan_exercise_progressions_training_plan_id_fkey"
            columns: ["training_plan_id"]
            isOneToOne: false
            referencedRelation: "training_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      training_plan_exercise_sets: {
        Row: {
          expected_reps: number
          expected_weight: number
          id: string
          set_index: number
          training_plan_exercise_id: string
        }
        Insert: {
          expected_reps: number
          expected_weight: number
          id?: string
          set_index: number
          training_plan_exercise_id: string
        }
        Update: {
          expected_reps?: number
          expected_weight?: number
          id?: string
          set_index?: number
          training_plan_exercise_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "training_plan_exercise_sets_training_plan_exercise_id_fkey"
            columns: ["training_plan_exercise_id"]
            isOneToOne: false
            referencedRelation: "training_plan_exercises"
            referencedColumns: ["id"]
          },
        ]
      }
      training_plan_exercises: {
        Row: {
          exercise_id: string
          id: string
          order_index: number
          training_plan_day_id: string
        }
        Insert: {
          exercise_id: string
          id?: string
          order_index: number
          training_plan_day_id: string
        }
        Update: {
          exercise_id?: string
          id?: string
          order_index?: number
          training_plan_day_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "training_plan_exercises_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "training_plan_exercises_training_plan_day_id_fkey"
            columns: ["training_plan_day_id"]
            isOneToOne: false
            referencedRelation: "training_plan_days"
            referencedColumns: ["id"]
          },
        ]
      }
      training_plans: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          user_id?: string
        }
        Relationships: []
      }
      training_sessions: {
        Row: {
          id: string
          session_date: string
          status: string
          training_plan_day_id: string | null
          training_plan_id: string
          user_id: string
        }
        Insert: {
          id?: string
          session_date?: string
          status?: string
          training_plan_day_id?: string | null
          training_plan_id: string
          user_id: string
        }
        Update: {
          id?: string
          session_date?: string
          status?: string
          training_plan_day_id?: string | null
          training_plan_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "training_sessions_training_plan_day_id_fkey"
            columns: ["training_plan_day_id"]
            isOneToOne: false
            referencedRelation: "training_plan_days"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "training_sessions_training_plan_id_fkey"
            columns: ["training_plan_id"]
            isOneToOne: false
            referencedRelation: "training_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          active_training_plan_id: string | null
          created_at: string | null
          first_name: string
          id: string
          updated_at: string | null
        }
        Insert: {
          active_training_plan_id?: string | null
          created_at?: string | null
          first_name: string
          id: string
          updated_at?: string | null
        }
        Update: {
          active_training_plan_id?: string | null
          created_at?: string | null
          first_name?: string
          id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_profiles_active_training_plan_fkey"
            columns: ["active_training_plan_id"]
            isOneToOne: false
            referencedRelation: "training_plans"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<
  SchemaName extends keyof Database = "public",
  TableName extends keyof (Database[SchemaName]["Tables"] & Database[SchemaName]["Views"]) = never
> = (Database[SchemaName]["Tables"] &
    Database[SchemaName]["Views"])[TableName] extends { Row: infer R }
      ? R
      : never

export type TablesInsert<
  SchemaName extends keyof Database = "public",
  TableName extends keyof Database[SchemaName]["Tables"] = never
> = Database[SchemaName]["Tables"][TableName] extends { Insert: infer I }
      ? I
      : never

export type TablesUpdate<
  SchemaName extends keyof Database = "public",
  TableName extends keyof Database[SchemaName]["Tables"] = never
> = Database[SchemaName]["Tables"][TableName] extends { Update: infer U }
      ? U
      : never

export type Enums<
  SchemaName extends keyof Database = "public",
  EnumName extends keyof Database[SchemaName]["Enums"] = never
> = Database[SchemaName]["Enums"][EnumName]

export type CompositeTypes<
  SchemaName extends keyof Database = "public",
  CompositeTypeName extends keyof Database[SchemaName]["CompositeTypes"] = never
> = Database[SchemaName]["CompositeTypes"][CompositeTypeName]

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
