export const sessionsSelectors = {
  header: {
    title: 'session-header-title',
    plan: 'session-header-plan',
    date: 'session-header-date',
    status: 'session-header-status',
  },
  set: {
    bubble: 'set-bubble',
    bubbleText: 'set-bubble-text',
    bubbleWeightText: 'set-bubble-weight-text',
  },
  warmup: {
    toggle: 'warmup-toggle-bubble',
    bubble: 'warmup-set-bubble',
    bubbleText: 'warmup-set-bubble-text',
    bubbleWeightText: 'warmup-set-bubble-weight-text',
  },
  dialogs: {
    sets: {
      title: 'add-edit-set-dialog-title',
      content: 'add-edit-set-dialog-content',
      repsInput: 'add-edit-set-dialog-reps-input',
      weightInput: 'add-edit-set-dialog-weight-input',
      saveButton: 'add-edit-set-dialog-save-button',
    },
    finishTime: {
      title: 'session-finish-time-dialog-title',
      content: 'session-finish-time-dialog-content',
      dateInput: 'session-finish-time-dialog-date-input',
      timeInput: 'session-finish-time-dialog-time-input',
      preview: 'session-finish-time-dialog-preview',
      futureError: 'session-finish-time-dialog-future-error',
      saveButton: 'session-finish-time-dialog-save-button',
      cancelButton: 'session-finish-time-dialog-cancel-button',
    },
    notes: {
      title: 'session-notes-dialog-title',
      content: 'session-notes-dialog-content',
      sessionInput: 'session-notes-dialog-session-input',
      planInput: 'session-notes-dialog-plan-input',
      saveButton: 'session-notes-dialog-save-button',
      cancelButton: 'session-notes-dialog-cancel-button',
    },
  },
  sessionCard: {
    navigateButton: 'session-card-navigate-button',
    notesButton: 'session-card-notes-button',
  },
  finishSheet: {
    container: 'session-finish-sheet',
    title: 'session-finish-sheet-title',
    now: 'session-finish-sheet-now',
    lastSet: 'session-finish-sheet-last-set',
    pick: 'session-finish-sheet-pick',
  },
  exerciseItem: 'session-exercise-item',
  timer: 'session-timer',
  completeButton: 'complete-session-button',
  notesButton: 'session-notes-button',
  errorNotice: 'session-error-notice',
};
