export const sessionsSelectors = {
  header: {
    title: 'session-header-title',
    plan: 'session-header-plan',
    date: 'session-header-date',
    status: 'session-header-status',
  },
  set: {
    bubble: 'set-bubble',
    bubbleText: 'set-bubble-text',
    bubbleWeightText: 'set-bubble-weight-text',
  },
  warmup: {
    toggle: 'warmup-toggle-bubble',
    bubble: 'warmup-set-bubble',
    bubbleText: 'warmup-set-bubble-text',
    bubbleWeightText: 'warmup-set-bubble-weight-text',
  },
  dialogs: {
    sets: {
      title: 'add-edit-set-dialog-title',
      content: 'add-edit-set-dialog-content',
      repsInput: 'add-edit-set-dialog-reps-input',
      weightInput: 'add-edit-set-dialog-weight-input',
      saveButton: 'add-edit-set-dialog-save-button',
    },
    plateCalculator: {
      title: 'plate-calculator-dialog-title',
      content: 'plate-calculator-dialog-content',
      stepHint: 'plate-calculator-step-hint',
      weightInput: 'plate-calculator-weight-input',
      decrementButton: 'plate-calculator-decrement',
      incrementButton: 'plate-calculator-increment',
      loading: 'plate-calculator-loading',
      shortfall: 'plate-calculator-shortfall',
      chips: 'plate-calculator-chips',
      chipPrefix: 'plate-calculator-chip-',
      ladderToggle: 'plate-calculator-ladder-toggle',
      unevenWarning: 'plate-calculator-uneven-warning',
      closeButton: 'plate-calculator-close-button',
    },
    notes: {
      title: 'session-notes-dialog-title',
      content: 'session-notes-dialog-content',
      sessionInput: 'session-notes-dialog-session-input',
      planInput: 'session-notes-dialog-plan-input',
      saveButton: 'session-notes-dialog-save-button',
      cancelButton: 'session-notes-dialog-cancel-button',
    },
  },
  sessionCard: {
    navigateButton: 'session-card-navigate-button',
    notesButton: 'session-card-notes-button',
  },
  exerciseItem: 'session-exercise-item',
  timer: 'session-timer',
  completeButton: 'complete-session-button',
  notesButton: 'session-notes-button',
  plateCalculatorButton: 'session-plate-calculator-button',
  errorNotice: 'session-error-notice',
};
