export const planEditSelectors = {
  metadata: 'plan-edit-metadata',
  name: 'plan-metadata-name',
  historyNotice: 'plan-metadata-history-notice',
  activeNotice: 'plan-metadata-active-notice',
  deactivateButton: 'plan-deactivate-button',
  addDayButton: 'plan-add-day-button',
  editButton: 'plan-edit-button',
  activateButton: 'plan-activate-button',
  errorNotice: 'plan-edit-error-notice',
  reorderDaysButton: 'plan-reorder-days-button',
  days: {
    item: 'plan-day-item',
    tab: 'plan-day-tab',
    menuButton: 'plan-day-menu-button',
    editButton: 'plan-edit-day-edit-button',
    addExerciseButton: 'plan-day-add-exercise-button',
  },
  exercises: {
    item: 'plan-exercise-item',
    name: 'plan-exercise-name',
    menuButton: 'plan-exercise-menu-button',
    deleteButton: 'plan-exercise-delete-button',
    archiveButton: 'plan-exercise-archive-button',
    addProgressionButton: 'plan-exercise-add-progression-button',
    editProgressionButton: 'plan-exercise-edit-progression-button',
    addSetButton: 'plan-exercise-add-set-button',
    dragHandle: 'plan-exercise-drag-handle',
  },
  sets: {
    item: 'plan-exercise-set-item',
    reps: 'plan-exercise-set-reps',
    weight: 'plan-exercise-set-weight',
    increaseWeightButton: 'plan-exercise-set-weight-increase',
    decreaseWeightButton: 'plan-exercise-set-weight-decrease',
    editButton: 'plan-exercise-set-edit-button',
  },
  dialogs: {
    reorderDays: {
      list: 'reorder-days-list',
      item: 'reorder-days-item',
      handle: 'reorder-days-handle',
      saveButton: 'reorder-days-save-button',
      cancelButton: 'reorder-days-cancel-button',
    },
  },
};
